<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.30" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ASP_Task.Application\ASP_Task.Application.csproj" />
    <ProjectReference Include="..\ASP_Task.Domain\ASP_Task.Domain.csproj" />
  </ItemGroup>

</Project>
